# permissions for end users to view plugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: plugin-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openshift-cli-manager2
    app.kubernetes.io/part-of: openshift-cli-manager2
    app.kubernetes.io/managed-by: kustomize
  name: plugin-viewer-role
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - plugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - plugins/status
  verbs:
  - get
